APP = 'assignment_schema'
DB_URL = 'postgresql://ui_test:ui_test@localhost:5432/ui_test'
JWT_SECRET = 'sr1ngw3lln0'
ACCESS_TOKEN_COOKIE_KEY = 'ACCESS-TOKEN'
CSRF_TOKEN_COOKIE_KEY = 'CSRF-TOKEN'
CSRF_TOKEN_HEADER_KEY = 'X-CSRF-TOKEN'
