version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ui_test
      POSTGRES_USER: ui_test
      POSTGRES_PASSWORD: ui_test
